import React, { useState, useMemo } from 'react'
import { useProject } from '../context/ProjectContext'
import { useAuth } from '../context/AuthContext'
import { Trophy, Medal, Zap, Star, Gift, RotateCcw, X, AlertTriangle, Search, Activity, ArrowUpDown, ChevronDown } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import confetti from 'canvas-confetti'

export default function Leaderboard() {
  const { userRole } = useAuth()
  const { members, adjustProductivityScore, resetAllProductivityScores, globalActivities } = useProject()

  // Modals & Controls State
  const [showManageModal, setShowManageModal] = useState(false)
  const [showResetConfirm, setShowResetConfirm] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [sortBy, setSortBy] = useState('highest') // highest, lowest, alphabetical

  // Manage XP Form State
  const [selectedUserId, setSelectedUserId] = useState('')
  const [xpAmount, setXpAmount] = useState(50)
  const [xpReason, setXpReason] = useState('')

  // Derived Data (Search & Sort)
  const filteredMembers = useMemo(() => {
    let result = [...members];

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(m => m.name.toLowerCase().includes(q));
    }

    result.sort((a, b) => {
      const xpA = a.productivityScore || 0;
      const xpB = b.productivityScore || 0;

      if (sortBy === 'highest') return xpB - xpA;
      if (sortBy === 'lowest') return xpA - xpB;
      if (sortBy === 'alphabetical') return a.name.localeCompare(b.name);
      return 0;
    });

    return result;
  }, [members, searchQuery, sortBy]);

  // Keep the absolute top 3 static for the podium
  const absoluteTopThree = useMemo(() => {
    return [...members].sort((a, b) => (b.productivityScore || 0) - (a.productivityScore || 0)).slice(0, 3);
  }, [members]);

  const isDefaultView = !searchQuery && sortBy === 'highest';
  const listMembers = isDefaultView ? filteredMembers.slice(3) : filteredMembers;

  // Filter global activities to show events related to XP or Leaderboard
  const recentXPActivities = useMemo(() => {
    return globalActivities
      .filter(a => {
        if (!a || !a.action) return false;

        const actionText = a.action.toLowerCase();

        // Match phrase generated by ProjectContext or any other manual log
        return actionText.includes('xp') ||
          actionText.includes('leaderboard') ||
          actionText.includes('score');
      })
      .slice(0, 5);
  }, [globalActivities]);

  const handleAwardXP = async (e) => {
    e.preventDefault()
    if (!selectedUserId || !xpAmount || !xpReason.trim()) return

    await adjustProductivityScore(selectedUserId, parseInt(xpAmount), xpReason.trim())

    if (parseInt(xpAmount) > 0) {
      confetti({
        particleCount: 150,
        spread: 80,
        origin: { y: 0.6 },
        colors: ['#45C1AA', '#F57D43', '#EAB308'],
        zIndex: 9999
      });
    }

    setShowManageModal(false)
    setSelectedUserId('')
    setXpAmount(50)
    setXpReason('')
  }

  const handleResetSeason = () => {
    resetAllProductivityScores()
    setShowResetConfirm(false)
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
  };

  return (
    <div className="p-8 h-full flex flex-col bg-base text-white overflow-y-auto relative">

      {/* Ambient background glow */}

      {/* Header with Admin Controls */}
      <div className="relative mb-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-4 z-10">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}>
          <h1 className="text-[26px] leading-tight font-semibold text-neutral-50 tracking-[-0.02em] mb-2 flex items-center gap-3">
            <Trophy className="text-yellow-500 drop-shadow-[0_0_15px_rgba(234,179,8,0.5)]" size={36} />
            Hall of Fame
          </h1>
          <p className="text-neutral-400 font-medium">Complete tasks and earn XP.</p>
        </motion.div>

        {userRole === 'admin' && (
          <motion.div
            initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}
            className="flex items-center gap-3"
          >
            <button
              onClick={() => setShowManageModal(true)}
              className="flex items-center gap-2 px-5 py-2.5 bg-accent-600 hover:bg-accent-500 text-white rounded-xl text-sm font-bold transition-all hover:-translate-y-0.5"
            >
              <Gift size={18} /> Manage XP
            </button>
            <button
              onClick={() => setShowResetConfirm(true)}
              className="flex items-center gap-2 px-4 py-2.5 bg-card border border-raised hover:bg-raised text-neutral-300 rounded-xl text-sm font-bold transition-all hover:-translate-y-0.5"
            >
              <RotateCcw size={18} /> New Season
            </button>
          </motion.div>
        )}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-8 relative z-10">

        {/* Main Content (Podium & List) */}
        <div className="xl:col-span-3 space-y-8">



          {/* Podium for Absolute Top 3 (Only show if default view) */}
          <AnimatePresence mode="wait">
            {isDefaultView && absoluteTopThree.length > 0 && (
              <motion.div
                key="podium"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9, height: 0, overflow: 'hidden' }}
                transition={{ duration: 0.5, type: "spring" }}
                className="flex justify-center items-end gap-2 sm:gap-6 pt-10 pb-6"
              >
                {/* Rank 2 */}
                {absoluteTopThree[1] && (
                  <motion.div
                    initial={{ y: 50, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.4, type: "spring" }}
                    className="flex flex-col items-center w-28 sm:w-36 group"
                  >
                    <div className="relative mb-5 transition-transform duration-300 group-hover:-translate-y-2">
                      <div className="w-16 h-16 sm:w-20 sm:h-20 rounded-full bg-neutral-800 border-2 border-neutral-300 flex items-center justify-center text-xl sm:text-2xl font-bold z-10 relative overflow-hidden">
                        {absoluteTopThree[1].avatar}
                                              </div>
                      <div className="absolute -bottom-3 -right-2 bg-neutral-200 text-neutral-900 w-8 h-8 rounded-full flex items-center justify-center font-bold border-4 border-base z-20 shadow-lg">2</div>
                    </div>
                    <p className="font-bold text-sm sm:text-base truncate w-full text-center text-neutral-200">{absoluteTopThree[1].name}</p>
                    <div className="flex items-center gap-1 text-neutral-300 font-bold text-xs sm:text-sm mb-3 bg-neutral-800/50 px-3 py-1 rounded-full mt-1 border border-neutral-700/50">
                      <Zap size={14} className="fill-neutral-400 text-neutral-400" /> {absoluteTopThree[1].productivityScore || 0}
                    </div>
                    <div className="w-full bg-card h-32 rounded-t-xl border border-b-0 border-raised border-t-2 border-t-neutral-400/70 flex items-start justify-center pt-5 transition-colors duration-300 group-hover:bg-raised">
                      <Medal className="text-neutral-400" size={36} />
                    </div>
                  </motion.div>
                )}

                {/* Rank 1 */}
                {absoluteTopThree[0] && (
                  <motion.div
                    initial={{ y: 80, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.2, type: "spring", stiffness: 200 }}
                    className="flex flex-col items-center w-36 sm:w-44 z-10 group"
                  >
                    <div className="relative mb-6 transition-transform duration-300 group-hover:-translate-y-2">
                      <motion.div
                        className="absolute -top-8 left-1/2 -translate-x-1/2 text-yellow-400 z-30"
                      >
                        <Star className="fill-yellow-400" size={32} />
                      </motion.div>
                      <div className="w-24 h-24 sm:w-28 sm:h-28 rounded-full bg-yellow-950/60 border-[3px] border-yellow-400 flex items-center justify-center text-3xl font-bold z-10 relative overflow-hidden">
                        {absoluteTopThree[0].avatar}
                                              </div>
                      <div className="absolute -bottom-4 -right-2 bg-yellow-400 text-yellow-950 w-10 h-10 rounded-full flex items-center justify-center font-bold border-4 border-base z-20 shadow-lg text-lg">1</div>
                    </div>
                    <p className="font-extrabold text-lg sm:text-xl truncate w-full text-center text-yellow-50">{absoluteTopThree[0].name}</p>
                    <div className="flex items-center gap-1.5 text-yellow-300 font-bold text-sm sm:text-base mb-4 bg-yellow-900/40 px-4 py-1.5 rounded-full mt-1 border border-yellow-500/30">
                      <Zap size={16} className="fill-yellow-400 text-yellow-400" /> {absoluteTopThree[0].productivityScore || 0} XP
                    </div>
                    <div className="w-full bg-card h-44 rounded-t-xl border border-b-0 border-raised border-t-2 border-t-yellow-400/80 flex items-start justify-center pt-6 transition-colors duration-300 group-hover:bg-raised">
                      <Trophy className="text-yellow-400" size={48} />
                    </div>
                  </motion.div>
                )}

                {/* Rank 3 */}
                {absoluteTopThree[2] && (
                  <motion.div
                    initial={{ y: 50, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.6, type: "spring" }}
                    className="flex flex-col items-center w-28 sm:w-36 group"
                  >
                    <div className="relative mb-5 transition-transform duration-300 group-hover:-translate-y-2">
                      <div className="w-16 h-16 sm:w-20 sm:h-20 rounded-full bg-orange-950/60 border-2 border-orange-500 flex items-center justify-center text-xl sm:text-2xl font-bold z-10 relative overflow-hidden">
                        {absoluteTopThree[2].avatar}
                                              </div>
                      <div className="absolute -bottom-3 -right-2 bg-orange-600 text-white w-8 h-8 rounded-full flex items-center justify-center font-bold border-4 border-base z-20 shadow-lg">3</div>
                    </div>
                    <p className="font-bold text-sm sm:text-base truncate w-full text-center text-orange-100">{absoluteTopThree[2].name}</p>
                    <div className="flex items-center gap-1 text-orange-300 font-bold text-xs sm:text-sm mb-3 bg-orange-950/60 px-3 py-1 rounded-full mt-1 border border-orange-800/50">
                      <Zap size={14} className="fill-orange-400 text-orange-400" /> {absoluteTopThree[2].productivityScore || 0}
                    </div>
                    <div className="w-full bg-card h-28 rounded-t-xl border border-b-0 border-raised border-t-2 border-t-orange-500/70 flex items-start justify-center pt-5 transition-colors duration-300 group-hover:bg-raised">
                      <Medal className="text-orange-400" size={32} />
                    </div>
                  </motion.div>
                )}
              </motion.div>
            )}
          </AnimatePresence>

          {/* Controls: Search & Sort */}
          <motion.div
            initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
            className="flex flex-col sm:flex-row gap-4 p-4 bg-card border border-raised rounded-2xl"
          >
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400" size={18} />
              <input
                type="text"
                placeholder="Search competitors..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2 bg-base/50 border border-raised focus:border-accent-500 rounded-xl text-sm focus:outline-none transition-colors"
                autoComplete="off"
              />
            </div>
            <div className="relative min-w-[180px]">
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400 flex items-center pr-2 border-r border-raised">
                <ArrowUpDown size={16} />
              </div>
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="w-full pl-12 pr-4 py-2 bg-base/50 border border-raised focus:border-accent-500 rounded-xl text-sm focus:outline-none transition-colors appearance-none cursor-pointer"
              >
                <option value="highest">Highest XP</option>
                <option value="lowest">Lowest XP</option>
                <option value="alphabetical">Name (A-Z)</option>
              </select>
              <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-neutral-500">
                <ChevronDown size={14} />
              </div>
            </div>
          </motion.div>

          {/* List Section */}
          <div className="bg-card rounded-2xl border border-raised/80 overflow-hidden">
            {listMembers.length > 0 ? (
              <motion.div
                variants={containerVariants}
                initial="hidden"
                animate="show"
                className="divide-y divide-raised/60"
              >
                {listMembers.map((member, index) => {
                  // Determine display rank based on sort/search state
                  let rankDisplay = '';
                  if (isDefaultView) {
                    rankDisplay = `#${index + 4}`;
                  } else {
                    // If sorted/searched, we might not want to show hardcoded ranks, 
                    // but showing absolute index + 1 is fine if it's visually just a counter
                    rankDisplay = `#${index + 1}`;
                  }

                  return (
                    <motion.div
                      key={member.id}
                      variants={itemVariants}
                      whileHover={{ scale: 1.01, backgroundColor: 'rgba(255, 255, 255, 0.03)' }}
                      className="flex items-center justify-between p-5 transition-colors group"
                    >
                      <div className="flex items-center gap-5">
                        <div className="w-10 text-lg font-bold text-edge text-center group-hover:text-neutral-400 transition-colors">
                          {rankDisplay}
                        </div>
                        <div className="w-12 h-12 rounded-full bg-neutral-700 flex items-center justify-center font-bold text-lg border border-neutral-600/30">
                          {member.avatar}
                        </div>
                        <div>
                          <p className="font-bold text-neutral-200 text-lg">{member.name}</p>
                          <p className="text-sm text-neutral-500 font-medium capitalize flex items-center gap-1.5">
                            {member.role === 'admin' && <Star size={12} className="text-accent-400" />}
                            {member.role || 'Member'}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 px-4 py-2 bg-accent-500/10 rounded-full border border-accent-500/20 group-hover:border-accent-500/40 transition-colors">
                        <Zap size={16} className="text-accent-400 fill-accent-400/30" />
                        <span className="font-bold text-accent-300">{member.productivityScore || 0} XP</span>
                      </div>
                    </motion.div>
                  );
                })}
              </motion.div>
            ) : (
              <motion.div
                initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="p-16 text-center text-neutral-500 bg-card flex flex-col items-center"
              >
                <Trophy size={48} className="mb-4 text-neutral-700" />
                <p className="text-lg font-medium">No members found.</p>
                {searchQuery && <p className="text-sm mt-1">Try changing your search query.</p>}
              </motion.div>
            )}
          </div>
        </div>

        {/* Sidebar: Activity Ticker */}
        <div className="xl:col-span-1">
          <motion.div
            initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.4 }}
            className="sticky top-8 bg-card/40 backdrop-blur-md rounded-2xl border border-raised/80 overflow-hidden"
          >
            <div className="p-5 border-b border-raised/60 flex items-center gap-3 bg-accent-900/10">
              <div className="w-8 h-8 rounded-full bg-accent-500/20 flex items-center justify-center">
                <Activity size={16} className="text-accent-400" />
              </div>
              <h3 className="font-bold text-neutral-100">Live XP Activity</h3>
            </div>

            <div className="p-5 space-y-6">
              {recentXPActivities.length > 0 ? (
                recentXPActivities.map((activity, idx) => (
                  <motion.div
                    key={activity._id || idx}
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: 0.5 + (idx * 0.1) }}
                    className="relative pl-6 before:absolute before:inset-y-0 before:left-[11px] before:w-px before:bg-raised last:before:hidden"
                  >
                    <div className="absolute left-0 top-1 w-6 h-6 rounded-full bg-card border border-edge flex items-center justify-center shadow-md">
                      <Zap size={10} className="text-yellow-500 fill-yellow-500/50" />
                    </div>
                    <div className="bg-base/50 rounded-xl p-3 border border-raised/50 hover:border-accent-500/30 transition-colors cursor-default group">
                      <p className="text-sm text-neutral-300 font-medium group-hover:text-white transition-colors">
                        <span className="font-bold text-accent-400">{activity.userName}</span> {activity.action}
                      </p>
                      <span className="text-xs text-neutral-600 mt-2 block font-medium">
                        {new Date(activity.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                  </motion.div>
                ))
              ) : (
                <div className="text-center py-8 text-neutral-500 text-sm">
                  <Activity size={24} className="mx-auto mb-3 text-neutral-600 opacity-50" />
                  No recent XP activity.
                </div>
              )}
            </div>
          </motion.div>
        </div>
      </div>

      {/* --- ADMIN MODALS --- */}
      <AnimatePresence>
        {/* Manage XP Modal */}
        {showManageModal && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center px-4"
          >
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setShowManageModal(false)} />
            <motion.form
              initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
              onSubmit={handleAwardXP}
              className="relative z-10 w-full max-w-md bg-card border border-edge rounded-2xl p-6"
            >
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-xl font-bold text-white flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-accent-500/20 flex items-center justify-center border border-accent-500/30">
                    <Gift className="text-accent-400" size={20} />
                  </div>
                  Manage XP
                </h3>
                <button type="button" onClick={() => setShowManageModal(false)} className="w-8 h-8 flex items-center justify-center rounded-full bg-base text-neutral-500 hover:text-white hover:bg-red-500/20 transition-colors"><X size={16} /></button>
              </div>

              <div className="space-y-6">
                <div>
                  <label className="text-xs text-accent-400 font-semibold uppercase tracking-[0.08em] mb-2 block">1. Select Member</label>
                  <select
                    value={selectedUserId}
                    onChange={(e) => setSelectedUserId(e.target.value)}
                    className="w-full bg-base border border-edge text-white rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-accent-500 focus:ring-1 focus:ring-accent-500 transition-shadow appearance-none cursor-pointer"
                  >
                    <option value="" disabled>Choose a champion...</option>
                    {members.map(m => <option key={m.id} value={m.id}>{m.name} • {m.productivityScore || 0} XP</option>)}
                  </select>
                </div>

                <div>
                  <label className="text-xs text-accent-400 font-semibold uppercase tracking-[0.08em] mb-2 block">2. Amount</label>
                  <div className="flex flex-wrap gap-2 mb-3">
                    {[50, 100, 200, -50].map(val => (
                      <button
                        key={val} type="button"
                        onClick={() => setXpAmount(val)}
                        className={`px-4 py-2 rounded-lg text-sm font-bold border transition-all ${xpAmount === val ? 'bg-accent-600 border-accent-500 text-white scale-105' : 'bg-base border-edge text-neutral-400 hover:text-white hover:border-neutral-500'}`}
                      >
                        {val > 0 ? `+${val}` : val}
                      </button>
                    ))}
                  </div>
                  <input
                    type="number"
                    value={xpAmount}
                    onChange={(e) => setXpAmount(e.target.value)}
                    placeholder="Custom amount"
                    className="w-full bg-base border border-edge text-white rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-accent-500 focus:ring-1 focus:ring-accent-500 transition-shadow"
                  />
                </div>

                <div>
                  <label className="text-xs text-accent-400 font-semibold uppercase tracking-[0.08em] mb-2 block">3. Reason</label>
                  <textarea
                    value={xpReason}
                    onChange={(e) => setXpReason(e.target.value)}
                    placeholder="e.g. Heroic bug fixing before deployment!"
                    className="w-full bg-base border border-edge text-white rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-accent-500 focus:ring-1 focus:ring-accent-500 transition-shadow h-24 resize-none"
                  />
                  <p className="text-[10px] text-neutral-500 mt-1.5 font-medium">This will be broadcasted to their notifications and the live ticker.</p>
                </div>
              </div>

              <div className="flex justify-end gap-3 mt-8 pt-5 border-t border-raised">
                <button type="button" onClick={() => setShowManageModal(false)} className="px-5 py-2.5 rounded-xl text-sm font-bold text-neutral-400 hover:bg-raised hover:text-white transition-colors">Cancel</button>
                <button
                  type="submit"
                  disabled={!selectedUserId || !xpAmount || !xpReason.trim()}
                  className="px-6 py-2.5 rounded-xl text-sm font-bold bg-accent-600 text-white hover:bg-accent-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                  <span className="flex items-center gap-2">
                    <Zap size={16} className="fill-white" /> Apply XP
                  </span>
                </button>
              </div>
            </motion.form>
          </motion.div>
        )}

        {/* Reset Season Confirmation Modal */}
        {showResetConfirm && (
          <motion.div
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center px-4"
          >
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setShowResetConfirm(false)} />
            <motion.div
              initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
              className="relative z-10 w-full max-w-md bg-card border border-red-500/30 rounded-2xl p-6"
            >
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 rounded-full bg-red-500/20 flex items-center justify-center border border-red-500/30 text-red-400">
                  <AlertTriangle size={24} />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white">Start New Season?</h3>
                  <p className="text-sm text-red-400 font-bold">WARNING: Destructive Action</p>
                </div>
              </div>
              <div className="bg-base border border-edge rounded-xl p-4 mb-6">
                <p className="text-neutral-300 text-sm leading-relaxed">
                  This will clear <strong className="text-white">all XP points</strong> for <strong className="text-white">every member</strong> and start a brand new season globally.
                  This action cannot be undone.
                </p>
              </div>
              <div className="flex justify-end gap-3">
                <button onClick={() => setShowResetConfirm(false)} className="px-5 py-2.5 rounded-xl text-sm font-bold text-neutral-400 hover:bg-raised hover:text-white transition-colors">Cancel</button>
                <button onClick={handleResetSeason} className="px-6 py-2.5 rounded-xl text-sm font-bold bg-red-600 text-white hover:bg-red-500 transition-all shadow-red-600/20">
                  Yes, Reset Everything
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  )
}